### ISSUE TITLE
Can't find API key

### ISSUE THREAD

**Issue by Ghostotw** [keithfancher/tvmv#10]
I had it working, then it quit when I opened a new PS window.
Windows 10, PS 7.4
Tried:
`tvmv mv -k API_KEY`
Threw an error, showed me the usage guide.
`tvmv mv --api-key API_KEY`
same result

Added TMDB_API_KEY to system env variables via the Windows env variable editor (as admin).
Put "tmdb-api-key" text files in both \.config\tvmv and ~\Roaming\tvmv\
Still says it can't find the API key.

**Comment by keithfancher** [comment]
For windows, the location of the API key file would be:

```
C:/Users/<user>/AppData/Roaming/tvmv/tmdb-api-key
```

Make sure that Windows isn't appending the `.txt` extension to the file, too... I believe it does that sometimes.

> Tried:
> `tvmv mv -k API_KEY`

This might be a silly question, but: was this the full command you typed? If so, you would need to specify the other params as well, like:

```
tvmv mv -k [YOUR_API_KEY_HERE] -n firefly -a
```

Let me know if the above works for you, and if not please post the full command and output here (redact your actual API key, of course!) and I'll take a look.

FWIW, I think I'm going to sidestep the API key requirement in the next version of `tvmv` by including a "default" API key. I'll still let people use their own if they want/need, but that way folks can truly get up and running with zero config. (Until the shared key starts hitting rate limits :smile: ...)

**Comment by keithfancher** [comment]
I've done some more testing in Windows and verified that `tvmv` can find the API key at the location I specified above. I'd need some more details to understand what's going wrong in your particular case.

But more importantly, I just released [a new version](https://github.com/keithfancher/tvmv/releases) of `tvmv` which doesn't require you to specify your API key at all ... so this should solve your issue as well! :tada: 

Please feel free to re-open this if you're still having problems, but I'm closing the issue for now. Thanks again for filing!
