### ISSUE TITLE
Can't rename files unless you rename a whole season

### ISSUE THREAD

**Issue by Emstar** [keithfancher/tvmv#2]
Thanks for the Windows binary. I set my API key as an env variable and got the bin installed. 

I tried a sample file and I think it identified the right show off my search term... But it wouldn't rename the file, because I didn't have _all_ the available episodes. 

```
Fetching show data from API...
Failed with: RenameError "Mismatched number of episodes (15) and files (1)"
```

Being able to rename an arbitrary number of files would be great.

**Comment by keithfancher** [comment]
> Being able to rename an arbitrary number of files would be great.

Yes! Check out the `-p` (`--allow-partial`) option. This is a little too buried [in the README](https://github.com/keithfancher/tvmv#matching-the-number-of-episodes-and-files), I think...

Note that this will only work if you have the _first_ n files, so it's still not completely arbitrary. The matching isn't smart enough yet to pick and choose specific episodes, it just assumes you have the first n contiguous episodes for a given season. (That limitation will likely go away in the future, though!)

**Comment by Emstar** [comment]
Ah now I see, sorry I missed that!

First _n_ is a pretty big limitation for my use case as my most frequent renaming use is adding new files as they appear. But... One step at a time. 

I'm subscribed to new releases and I'll keep messing with it!

**Comment by keithfancher** [comment]
> Ah now I see, sorry I missed that!

No worries! The README is kind of... a bit much right now. I should find a way to call out the CLI options more clearly.

> First n is a pretty big limitation for my use case as my most frequent renaming use is adding new files as they appear. But... One step at a time.

That's great feedback to have. I tend to grab/rip whole seasons at a time, so I didn't think about this much up front. But seems like something I should get figured out soon!

> I'm subscribed to new releases and I'll keep messing with it!

Awesome!
