### ISSUE TITLE
Expand API key section of the readme

### ISSUE THREAD

**Issue by jiminorris** [keithfancher/tvmv#7]
I'm on Debian testing, and placing a text file containing the API key in $XDG_CONFIG_HOME/tvmv/tmdb-api-key doesn't seem to work.

Passing the key using the -k switch works fine.

I presume I'm being dense, but should the key be held in a particular type or format not currently noted in the readme?

**Comment by keithfancher** [comment]
Thank you for pointing this out! It appears that this env variable is often *not* explicitly defined. I'll update the README!

It looks like if `$XDG_CONFIG_HOME` is not defined [it defaults to](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables) `~/.config/`. So if you put your API key in a file at `~/.config/tvmv/tmdb-api-key`, it should work for you.

Please let me know if it doesn't! (And let me know what the specific error message is as well.

**Comment by keithfancher** [comment]
By the way, I just released [a new version](https://github.com/keithfancher/tvmv/releases) of `tvmv` which doesn't require you to use your own API at all, so hopefully this solves any remaining issues you might have (albeit in a slightly roundabout way!) :smile: 

Closing this out for now, but feel free to re-open if you're still having issues!
